services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
    ports:
      - "5432:5432"
    volumes:
      - walletdb_pg_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walletuser"]
      interval: 5s
      retries: 5
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

volumes:
  walletdb_pg_data: